# Generated by Django 3.1 on 2020-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='media', verbose_name='Profile Picture'),
        ),
    ]
