# Generated by Django 3.1 on 2020-09-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200914_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
