# Generated by Django 3.1 on 2020-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200916_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='media/profile/', verbose_name='Profile Picture'),
        ),
    ]
