# Generated by Django 3.1 on 2020-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theswitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopost',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='audiopost',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videopost',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videopost',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
