# Generated by Django 3.1 on 2020-08-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theswitch', '0002_auto_20200822_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiopost',
            old_name='thumnail',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='videopost',
            old_name='thumnail',
            new_name='cover',
        ),
    ]
