# Generated by Django 3.1 on 2020-09-18 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theswitch', '0004_auto_20200909_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopost',
            name='likes',
            field=models.ManyToManyField(related_name='audio_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videopost',
            name='likes',
            field=models.ManyToManyField(related_name='video_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
