# Generated by Django 3.1 on 2020-09-28 15:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theswitch', '0007_audiocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiopost',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='audio_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiopost',
            name='upload',
            field=models.FileField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='upload',
            field=models.FileField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
